CREATE TABLE IF NOT EXISTS cohorts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    meta_label VARCHAR(120) NULL,
    excerpt VARCHAR(500) NULL,
    description TEXT NULL,
    content LONGTEXT NULL,
    video_source_type ENUM('link', 'upload') NOT NULL DEFAULT 'link',
    video_url VARCHAR(500) NULL,
    video_path VARCHAR(500) NULL,
    poster_image VARCHAR(500) NULL,
    resource_label VARCHAR(120) NULL,
    resource_url VARCHAR(500) NULL,
    takeaways_json LONGTEXT NULL,
    status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    published_at DATETIME NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY cohorts_slug_unique (slug),
    KEY cohorts_status_sort_index (status, sort_order, published_at),
    KEY cohorts_featured_index (is_featured, status),
    KEY cohorts_created_by_index (created_by),
    KEY cohorts_updated_by_index (updated_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
