CREATE TABLE IF NOT EXISTS events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    meta_label VARCHAR(120) NULL,
    description TEXT NULL,
    event_date DATE NULL,
    event_time_label VARCHAR(60) NULL,
    location VARCHAR(180) NULL,
    video_source_type ENUM('link', 'upload') NOT NULL DEFAULT 'link',
    video_url VARCHAR(500) NULL,
    video_path VARCHAR(500) NULL,
    poster_image VARCHAR(500) NULL,
    registration_label VARCHAR(120) NULL,
    registration_url VARCHAR(500) NULL,
    status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
    sort_order INT NOT NULL DEFAULT 0,
    published_at DATETIME NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY events_status_sort_index (status, sort_order, published_at),
    KEY events_date_index (event_date),
    KEY events_created_by_index (created_by),
    KEY events_updated_by_index (updated_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
